// Generated by CoffeeScript 1.8.0
(function() {
  var Dir, dirArr, type, watchFile;

  watchFile = require('./lib/watchFile');

  Dir = require('./dslib/directorySet');

  type = '';

  dirArr = [];

  process.argv.forEach(function(_v, _i) {
    if (_i !== 0 && _i !== 1) {
      if (_i === 2) {
        type = _v;
      } else {
        dirArr[_i - 3] = new Dir(_v, '');
      }
    }
  });

  if (type === 'lan_server ' || type === 'lan_client') {
    dirArr = dirArr[0];
  }

  watchFile.setDirs(dirArr, type);

}).call(this);

//# sourceMappingURL=index.js.map
