// Generated by CoffeeScript 1.8.0
(function() {
  var Dir, dirArr, type, watchFile;

  watchFile = require('./files/watchFile');

  Dir = require('./jslibs/fileTree');

  type = '';

  dirArr = [];

  process.argv.forEach(function(_v, _i) {
    if (_i !== 0 && _i !== 1) {
      if (_i === 2) {
        type = _v;
      } else {
        dirArr[_i - 3] = new Dir(_v);
      }
    }
  });

  watchFile.setDirs(dirArr);

}).call(this);

//# sourceMappingURL=index.js.map
