// Generated by CoffeeScript 1.8.0
(function() {
  var Node, fs, n1, n2, root;

  fs = require('fs');

  Node = require('./jslibs/directorySet.js');

  root = new Node([1, 2, 3]);

  n1 = new Node('a');

  n2 = new Node('b');

  root.push(n1);

  root.push(n2);

  root.display();

}).call(this);

//# sourceMappingURL=test.js.map
