// Generated by CoffeeScript 1.8.0
(function() {
  var client, net;

  net = require('net');

  client = net.connect({
    port: 8888
  }, function() {
    var i, si;
    console.log('client connected');
    client.write('world');
    i = 0;
    si = setInterval(function() {
      return client.write('number is ' + i++);
    }, 1000);
    return setTimeout(function() {
      clearInterval(si);
      return client.end();
    }, 3000);
  });

  client.on('data', function(_data) {
    return console.log(_data.toString());
  });

  client.on('end', function() {
    return console.log('client disconnected');
  });

}).call(this);

//# sourceMappingURL=testConnectTo.js.map
