// Generated by CoffeeScript 1.8.0
(function() {
  var Dir;

  Dir = (function() {
    function Dir(path) {
      this.path = path;
      this.index = 0;
      this.files = [];
      this.childes = [];
    }

    Dir.prototype.append = function(_node) {
      if (_node.constructor !== Dir) {
        return false;
      }
      this.childes.push(_node);
      return _node.index = this.childes.length - 1;
    };

    Dir.prototype.push = function(_f) {
      if (_f) {
        if (_f.constructor === Array) {
          return this.files = this.files.concat(_f);
        } else {
          return this.files.push(_f);
        }
      }
    };

    Dir.prototype.searchFile = function(_filename) {
      var c, _i, _len, _ref;
      if (!_filename) {
        return false;
      }
      if (this.files.indexOf(_filename) === -1) {
        if (this.childes) {
          _ref = this.childes;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            c = _ref[_i];
            return c.searchFile(_filename);
          }
        } else {
          return null;
        }
      } else {
        return this;
      }
    };

    Dir.prototype.display = function() {
      var c, _i, _len, _ref, _results;
      console.log(this.path, "->", this.files);
      _ref = this.childes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        c = _ref[_i];
        _results.push(c.display());
      }
      return _results;
    };

    return Dir;

  })();

  module.exports = Dir;

}).call(this);

//# sourceMappingURL=fileTree.js.map
