// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    syncType: {
      SYNC_TO_LOCAL: 'local',
      SYNC_TO_LAN_S: 'lan_server',
      SYNC_TO_LAN_C: 'lan_client'
    }
  };

}).call(this);

//# sourceMappingURL=system.js.map
